cours/urls.py
from django.urls import path
from . import views

# Déclaration du namespace pour l'application 'cours'
app_name = 'cours'

# Liste des routes URL (urlpatterns)
urlpatterns = [
    # Route pour la page d'accueil (home)
    path('', views.home, name='home'),  # Cette URL correspond à la vue 'home'

    # Route pour la page de connexion
    path('login/', views.login_system, name='login'),  # Cette URL correspond à la vue 'login_system'

    # Route pour la page d'inscription
    path('register/', views.register, name='register'),  # Cette URL correspond à la vue 'register'

    # Route pour afficher les cours de l'utilisateur connecté
    path('mes_cours/', views.mes_cours, name='mes_cours'),  # Cette URL correspond à la vue 'mes_cours'

    # Route pour ajouter un nouveau cours
    path('add_cours/', views.add_cours, name='add_cours'),  # Cette URL correspond à la vue 'add_cours'

    # Route pour modifier un cours existant, l'ID du cours est passé en paramètre
    path('update_cours/<int:id>/', views.update_cours, name='update_cours'),  # Cette URL correspond à la vue 'update_cours'

    # Route pour supprimer un cours, l'ID du cours est passé en paramètre
    path('delete_cours/<int:id>/', views.delete_cours, name='delete_cours'),  # Cette URL correspond à la vue 'delete_cours'
]

gestion_cours/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cours.urls'))
]

cours/models.py
from django.db import models
from django.contrib.auth.models import User

# Définition du modèle Cours
class Cours(models.Model):
    # Relation entre le cours et l'utilisateur (enseignant)
    # Chaque cours est lié à un enseignant via une clé étrangère (ForeignKey)
    # Si l'enseignant est supprimé, tous les cours associés seront également supprimés (on_delete=models.CASCADE)
    enseignant = models.ForeignKey(User, on_delete=models.CASCADE)
    
    # Le nom du cours (une chaîne de caractères avec une limite de 100 caractères)
    nom = models.CharField(max_length=100)
    
    # Une description du cours, sans limite de longueur
    description = models.TextField()
    
    # Date et heure de création du cours (remplie automatiquement lors de la création)
    created_at = models.DateTimeField(auto_now_add=True)
    
    # Date et heure de la dernière modification du cours (mise à jour automatiquement à chaque modification)
    updated_at = models.DateTimeField(auto_now=True)
    
    # Méthode pour afficher le nom du cours comme représentation sous forme de chaîne
    def __str__(self) -> str:
        return self.nom

cours/forms.py
from django import forms
from .models import *

# Définition du formulaire pour le modèle 'Cours'
class CoursForm(forms.ModelForm):

    # Champ pour le nom du cours
    # - CharField est utilisé pour des champs de texte courts
    # - Le widget TextInput permet de personnaliser l'apparence du champ via des attributs HTML
    nom = forms.CharField(
        label="Nom du cours",  # Le texte du label affiché pour ce champ
        widget=forms.TextInput(attrs={
            'class': "w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500",  # Classe CSS pour le style du champ
        })
    )

    # Champ pour la description du cours
    # - CharField avec un widget Textarea permet d'avoir une zone de texte multi-lignes
    description = forms.CharField(
        label="Description du cours",  # Le texte du label pour ce champ
        widget=forms.Textarea(attrs={
            'class': "w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500",  # Classes CSS pour le style du champ
            'rows': '4'  # Définition de la taille visible du textarea avec 4 lignes
        })
    )
    
    # Classe Meta pour lier ce formulaire au modèle et spécifier les champs
    class Meta:
        model = Cours  # Le modèle associé à ce formulaire est 'Cours'
        fields = ('nom', 'description')  # Les champs du modèle à inclure dans le formulaire

cours/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import *
from .forms import *

# Vue de la page d'accueil
def home(request):
    # Cette vue affiche simplement la page d'accueil du site web.
    return render(request, 'cours/home.html')

# Vue pour la gestion de la connexion
def login_system(request):
    # Si la requête est de type POST (soumission du formulaire de connexion)
    if request.method == 'POST':
        # Récupération des données du formulaire
        email = request.POST.get('email')
        password = request.POST.get('password')
        
        # Recherche de l'utilisateur correspondant à l'email fourni
        users = User.objects.filter(email=email)
        if users.exists():  # Si l'utilisateur existe
            user = users.first()
            
            # Authentification de l'utilisateur avec son nom d'utilisateur et son mot de passe
            user_auth = authenticate(
                request, 
                username=user.username, 
                password=password
            )
            if user_auth:  # Si l'authentification est réussie
                # Connexion de l'utilisateur et redirection vers la page "mes cours"
                login(request, user_auth)
                return redirect('cours:mes_cours')
            else:
                # Affichage d'un message d'erreur si les informations sont incorrectes
                messages.error(request, 'Email et/ou mot de passe incorrect')
                return redirect('cours:login')
        else:
            # Affichage d'un message d'erreur si l'email n'est pas reconnu
            messages.error(request, 'Email et/ou mot de passe incorrect')
            return redirect('cours:login')
    
    # Si la requête est de type GET, on affiche la page de connexion
    return render(request, 'cours/login.html')

# Vue pour l'inscription d'un nouvel utilisateur
def register(request):
    # Si la requête est de type POST (soumission du formulaire d'inscription)
    if request.method == 'POST':
        # Récupération des données du formulaire
        nom_complet = request.POST.get('nom_complet')
        email = request.POST.get('email')
        password = request.POST.get('password')
        
        # Vérification de l'existence d'un compte avec cet email
        users = User.objects.filter(email=email)
        if users.exists():  # Si un compte existe déjà avec cet email
            messages.error(request, 'Un compte avec cette adresse email existe déjà')
            return redirect('cours:register')
        else:  # Création d'un nouveau compte utilisateur
            user = User(
                username=nom_complet,
                email=email,
            )
            user.set_password(password)  # Définition du mot de passe de l'utilisateur
            user.save()  # Sauvegarde du compte utilisateur dans la base de données
            
            messages.success(request, 'Compte créé avec succès')
            return redirect('cours:login')
        
    # Si la requête est de type GET, on affiche la page d'inscription
    return render(request, 'cours/register.html')

# Vue pour l'affichage des cours de l'utilisateur connecté
@login_required  # Cette vue nécessite que l'utilisateur soit connecté
def mes_cours(request):
    # Récupération des cours de l'enseignant connecté et tri par nom
    cours = Cours.objects.filter(enseignant=request.user).order_by('nom')
    context = {
        'cours': cours  # Les cours sont passés au contexte pour être affichés dans le template
    }
    return render(request, 'cours/mes_cours.html', context)

# Vue pour ajouter un nouveau cours
@login_required
def add_cours(request):
    # Si la requête est de type POST (soumission du formulaire d'ajout de cours)
    if request.method == 'POST':
        cours_form = CoursForm(request.POST)
        if cours_form.is_valid():
            cours = cours_form.save(commit=False)  # On ne sauvegarde pas encore le cours
            cours.enseignant = request.user  # On assigne l'enseignant connecté au cours
            cours.save()  # Sauvegarde du cours
            messages.success(request, "Le nouveau cours a bien été ajouté")
            return redirect('cours:mes_cours')
    else:
        cours_form = CoursForm()  # Formulaire vide pour l'ajout de cours
        
    context = {
        'cours_form': cours_form
    }
    return render(request, 'cours/cours_form.html', context)

# Vue pour modifier un cours existant
@login_required
def update_cours(request, id):
    cours = Cours.objects.get(id=id)  # Récupération du cours à modifier
    # Vérification que l'utilisateur connecté est bien l'enseignant du cours
    if cours.enseignant != request.user:
        messages.error(request, "Vous ne pouvez pas modifier un cours qui ne vous appartient pas")
        return redirect('cours:mes_cours')
    
    # Si la requête est de type POST (soumission du formulaire de modification)
    if request.method == 'POST':
        cours_form = CoursForm(request.POST, instance=cours)
        if cours_form.is_valid():
            cours_update = cours_form.save(commit=False)
            cours_update.enseignant = request.user  # On s'assure que l'enseignant reste le même
            cours_update.save()  # Sauvegarde des modifications
        
            messages.success(request, f"Le cours {cours.nom} a bien été modifié")
            return redirect('cours:mes_cours')
    else:
        cours_form = CoursForm(instance=cours)  # Formulaire pré-rempli avec les données du cours
        
    context = {
        'cours_form': cours_form,
        'cours': cours
    }
    return render(request, 'cours/cours_form.html', context)

# Vue pour supprimer un cours
@login_required
def delete_cours(request, id):
    cours = Cours.objects.get(id=id)  # Récupération du cours à supprimer
    # Vérification que l'utilisateur connecté est bien l'enseignant du cours
    if cours.enseignant != request.user:
        messages.error(request, "Vous ne pouvez pas supprimer un cours qui ne vous appartient pas")
    else:
        messages.success(request, f"La suppression du cours {cours.nom} s'est bien passée")
        cours.delete()  # Suppression du cours
    
    return redirect('cours:mes_cours')

templates/cours/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body class="h-screen flex flex-col lg:flex-row">
    <!-- Sidebar -->
    <div class="w-full lg:w-1/4 h-1/3 lg:h-full lg:block md:hidden sm:hidden bg-cover bg-center" style="background-image: url('{% static 'img/bg.png' %}');">
        <div class="relative flex items-center justify-center h-full">
            <div class="text-center p-3 h-full w-1/3 content-center space-y-16">
                <img src="{% static 'img/logo.png' %}" alt="Logo" class="w-50 h-30 mx-auto">
            </div>
        </div>
    </div>
    
    <!-- Main content -->
    <div class="w-full lg:w-3/4 h-full p-8 space-y-6 rounded-lg bg-gray-100">
        <header class="bg-white">
            <nav class="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8" aria-label="Global">
                <div class="flex lg:flex-1">
                    <a href="{% url 'cours:mes_cours' %}" class="-m-1.5 p-1.5 hover:text-primary">
                        <span class="self-center text-xl font-semibold sm:text-xl whitespace-nowrap dark:text-white">
                            ISTA-GOMA
                        </span>
                    </a>
                </div>
                <div class="flex lg:hidden">
                    <button id="mobile-menu-button" type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
                        <span class="sr-only">Open main menu</span>
                        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                        </svg>
                    </button>
                </div>
                <div class="hidden lg:flex lg:gap-x-12">
                    <a href="{% url 'cours:mes_cours' %}" class="text-sm font-semibold leading-6 text-gray-900 active">Mes cours</a>
                    <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Séances</a>
                    <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Présences</a>
                </div>
                <div class="hidden lg:flex lg:flex-1 lg:justify-end">
                    <a href="{% url 'cours:login' %}" class="text-sm font-semibold leading-6 text-gray-900">Mon compte</a>
                </div>
            </nav>
            
            <!-- Mobile menu -->
            <div id="mobile-menu" class="lg:hidden hidden" role="dialog" aria-modal="true">
                <div class="fixed inset-0 z-10"></div>
                <div class="fixed inset-y-0 right-0 z-10 w-full overflow-y-auto bg-white px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10">
                    <div class="flex items-center justify-between">
                        <a href="{% url 'cours:mes_cours' %}" class="-m-1.5 p-1.5 hover:text-primary">
                            <span class="self-center text-xl font-semibold sm:text-xl whitespace-nowrap dark:text-white">
                                ISTA-GOMA
                            </span>
                        </a>
                        <button id="mobile-menu-close" type="button" class="-m-2.5 rounded-md p-2.5 text-gray-700">
                            <span class="sr-only">Close menu</span>
                            <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                            </svg>
                        </button>
                    </div>
                    <div class="mt-6 flow-root">
                        <div class="-my-6 divide-y divide-gray-500/10">
                            <div class="space-y-2 py-6">
                                <a href="{% url 'cours:mes_cours' %}" class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50 active">Mes cours</a>
                                <a href="#" class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Séances</a>
                                <a href="#" class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Présences</a>
                            </div>
                            <div class="py-6">
                                <a href="{% url 'cours:login' %}" class="-mx-3 block rounded-lg px-3 py-2.5 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Se déconnecter</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <div class="">
            {% block content %}{% endblock content %}
        </div>
    </div>

    <!-- JavaScript for mobile menu toggle -->
    <script>
        const mobileMenuButton = document.getElementById('mobile-menu-button');
        const mobileMenu = document.getElementById('mobile-menu');
        const mobileMenuClose = document.getElementById('mobile-menu-close');

        mobileMenuButton.addEventListener('click', () => {
            mobileMenu.classList.toggle('hidden');
        });

        mobileMenuClose.addEventListener('click', () => {
            mobileMenu.classList.toggle('hidden');
        });
    </script>
</body>
</html>

templates/cours/cours_form.html
{% extends 'cours/base.html' %}  <!-- Étend le template de base pour la page -->

{% block title %}
    {% if cours %}
        Mise à jour du cours {{ cours.nom }}  <!-- Titre dynamique pour la mise à jour d'un cours existant -->
    {% else %}
        Nouveau cours  <!-- Titre pour la création d'un nouveau cours -->
    {% endif %}
{% endblock title %}

{% block content %}
    <div class="max-w-4xl px-4 py-4 mx-auto lg:py-8">
        <h2 class="mb-5 text-xl font-bold text-gray-900 dark:text-white">
            {% if cours %}
                Mise à jour du cours {{ cours.nom }}  <!-- Affiche le nom du cours lors de la mise à jour -->
            {% else %}
                Nouveau cours  <!-- Titre pour l'ajout d'un nouveau cours -->
            {% endif %}
        </h2>
        <form action="" method="post" enctype="multipart/form-data">  <!-- Formulaire pour soumettre les données -->
            <div class="grid gap-4 mb-4 sm:gap-6 sm:mb-5">
                {% if cours_form.non_field_errors %}
                    <!-- Affiche les erreurs non spécifiques au champ -->
                    {% for error in cours_form.non_field_errors %}
                        <div id="alert-2" class="flex items-center p-4 mb-4 text-red-800 rounded-lg bg-red-50 dark:bg-gray-700 dark:text-red-400" role="alert">
                            <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                            </svg>
                            <span class="sr-only">Error</span>
                            <div class="ms-3 text-sm font-medium">
                                {{ error }}  <!-- Affiche le message d'erreur -->
                            </div>
                            <button type="button" class="ms-auto -mx-1.5 -my-1.5 bg-red-50 text-red-500 rounded-lg focus:ring-2 focus:ring-red-400 p-1.5 hover:bg-red-200 inline-flex items-center justify-center h-8 w-8 dark:bg-gray-800 dark:text-red-400 dark:hover:bg-gray-700" data-dismiss-target="#alert-2" aria-label="Close">
                                <span class="sr-only">Close</span>
                                <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                                </svg>
                            </button>
                        </div>
                    {% endfor %}
                {% endif %}
                {% csrf_token %}  <!-- Token de sécurité pour le formulaire -->
                {% for field in cours_form %}
                    <div class="sm:col-span-2">  <!-- Colonne pour chaque champ du formulaire -->
                        {{ field.label_tag }}  <!-- Étiquette du champ -->
                        {{ field }}  <!-- Champ de formulaire -->
                        {% if field.help_text %}
                            <span class="form-text mt-0">{{ field.help_text }}</span>  <!-- Texte d'aide si présent -->
                        {% endif %}
                        {% if field.errors %}
                            <!-- Affiche les erreurs spécifiques au champ -->
                            <div id="alert-2" class="flex items-center p-3 mt-3 text-red-800 rounded-lg bg-red-50 dark:bg-gray-700 dark:text-red-400" role="alert">
                                <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                                    <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                                </svg>
                                <span class="sr-only">Error</span>
                                <div class="ms-3 text-sm font-medium">
                                    {% for error in field.errors %}
                                        <p> {{ error }} </p>  <!-- Affiche chaque erreur -->
                                    {% endfor %}
                                </div>
                                <button type="button" class="ms-auto -mx-1.5 -my-1.5 bg-red-50 text-red-500 rounded-lg focus:ring-2 focus:ring-red-400 p-1.5 hover:bg-red-200 inline-flex items-center justify-center h-5 w-5 dark:bg-gray-800 dark:text-red-400 dark:hover:bg-gray-700" data-dismiss-target="#alert-2" aria-label="Close">
                                    <span class="sr-only">Close</span>
                                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                                    </svg>
                                </button>
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
            <div class="flex justify-between space-x-4">
                <button type="submit" href="javascript:history.back()" class="text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-600">Annuler</button>
                <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
                    Enregistrer  <!-- Bouton pour soumettre le formulaire -->
                </button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/cours/home.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <section class="relative h-screen bg-cover bg-center" style="background-image: url('{% static 'img/bg.png' %}'); background-repeat: no-repeat;">
        <div class="absolute inset-0 bg-black opacity-50"></div>
        <div class="relative flex items-center justify-center h-full">
            <div class="text-center p-3 h-full w-1/3 content-center space-y-16">
                <img src="{% static 'img/logo.png' %}" alt="Logo" class="w-25 h-20 mx-auto mb-6">
                <p class="text-lg text-white">
                    Bienvenue sur la plateforme de gestion des cours pour l’ISTA-GOMA
                </p>
                <p class="text-lg text-white">
                    <a href="{% url 'cours:login' %}" class="px-6 py-1.5 bg-primary rounded-lg shadow transition">
                        Commencer
                    </a>
                </p>
            </div>
        </div>
    </section>
</body>
</html>

templates/cours/mes_cours.html
{% extends 'cours/base.html' %}

{% block title %}Mes cours{% endblock title %}

{% block content %}
    <div class="flex items-center justify-between mb-2">
        <h2 class="text-2xl font-bold">Mes cours</h2>
        <a href="{% url 'cours:add_cours' %}" class="px-6 py-1.5 bg-primary text-white rounded-md shadow hover:bg-blue-500 transition">
            Nouveau cours
        </a>
    </div>
    {% if messages %}
        <div class="p-4 mb-4 text-2sm text-center text-black-800 rounded-lg bg-yellow-50 dark:bg-gray-800" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endif %}
    {% if cours %}
        <div class="overflow-x-auto">
            <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-4 py-3">Nom</th>
                        <th scope="col" class="px-4 py-3">Desciption</th>
                        <th scope="col" class="px-4 py-3">Date création</th>
                        <th scope="col" class="px-4 py-3"></th>
                        <th scope="col" class="px-4 py-3"></th>
                    </tr>
                </thead>
                <tbody id="myTable">
                    {% for course in cours %}
                        <tr class="border-b dark:border-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700">
                            <td class="px-4 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                {{course.nom}}
                            </td>
                            <td class="px-4 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                {{course.description}}
                            </td>
                            <td class="px-4 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                {{course.created_at}}
                            </td>
                            <td class="px-4 py-2">
                                <a href="{% url 'cours:update_cours' course.id %}" class="px-6 py-1.5 bg-primary text-white rounded-md shadow hover:bg-blue-500 transition">
                                    Modifier
                                </a>
                            </td>
                            <td class="px-4 py-2">
                                <a onclick="return confirm('Voulez-vous vraiment supprimer ce cours')" href="{% url 'cours:delete_cours' course.id %}" class="text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-1.5 text-center inline-flex items-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800">
                                    Supprimer
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <p class="text-gray-600">
            Aucun cours trouvé pour vous
        </p>
    {% endif %}
{% endblock content %}